name: 'terraform-mt-action-24'
 
on:
  push:
    branches:
    - demo-branch
  pull_request:
 
jobs:
    terraform-plan:
        name: 'Terraform plan'
        env:
            ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

        runs-on: ubuntu-latest
        environment: production
    
        defaults:
         run:
            shell: bash
    
        steps:
        # Checkout the repository to the GitHub Actions runner
    
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: 'bash scripts 01'
          run: |
            echo "welcome to actions"
            cd terraform-script
            pwd

        # - name: 'Terraform Format'
        #   uses: hashicorp/terraform-github-actions@master
        #   with:
        #     tf_actions_version: 1.4.0
        #     tf_actions_subcommand: 'fmt'
        #     tf_actions_working_dir: "terraform-script"
            
        - name: 'Terraform Init'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 1.4.0
            tf_actions_subcommand: 'init'
            tf_actions_working_dir: "terraform-script"
    
        - name: 'Terraform Validate'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 1.4.0
            tf_actions_subcommand: 'validate'
            tf_actions_working_dir: "terraform-script"
            
        - name: 'Terraform Plan'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 1.4.0
            tf_actions_subcommand: 'plan'
            tf_actions_working_dir: "terraform-script"
    

    terraform-apply:
        needs: [terraform-plan]
        name: 'Terraform apply'
        env:
            ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

        runs-on: ubuntu-latest
        environment: production
    
        defaults:
         run:
            shell: bash
        
        steps:
            # Checkout the repository to the GitHub Actions runner
        
        - name: Checkout
          uses: actions/checkout@v2
            
        - name: bash scripts
          run: |
                echo "welcome to actions"
                cd terraform-script
                pwd

        # - name: 'Terraform Format'
        #   uses: hashicorp/terraform-github-actions@master
        #   with:
        #         tf_actions_version: 1.4.0
        #         tf_actions_subcommand: 'fmt'
        #         tf_actions_working_dir: "terraform-script"
                
        - name: 'Terraform Init'
          uses: hashicorp/terraform-github-actions@master
          with:
                tf_actions_version: 1.4.0
                tf_actions_subcommand: 'init'
                tf_actions_working_dir: "terraform-script"
        
        - name: 'Terraform Validate'
          uses: hashicorp/terraform-github-actions@master
          with:
                tf_actions_version: 1.4.0
                tf_actions_subcommand: 'validate'
                tf_actions_working_dir: "terraform-script"
                
        - name: 'Terraform Plan'
          uses: hashicorp/terraform-github-actions@master
          with:
                tf_actions_version: 1.4.0
                tf_actions_subcommand: 'plan'
                tf_actions_working_dir: "terraform-script"
        
        - name: Terraform Apply
        # if: github.ref == 'refs/heads/main'
          uses: hashicorp/terraform-github-actions@master
          with:
                tf_actions_version: 1.4.0
                tf_actions_subcommand: 'apply'
                tf_actions_working_dir: "terraform-script" 


